name: Repository dispatch of Tests
on:
  workflow_run:
    workflows: [Tests]
    types: [completed]

jobs:
  workflow-dispatch:
    name: repo dispatch event with conclusion
    runs-on: ubuntu-latest
    steps:
      - name: repo dispatch
        uses: tonyhallett/workflow-run-conclusion-dispatch-action@v1.0.0
        with:
          GITHUB_PAT: ${{ secrets.PAT }}